version: "3.4"

services:
  site:
    image: bvsite:local
    build:
      context: .
    container_name: bvsite
    volumes:
      - ./src:/app/src
      - ./projects:/app/projects
      - ./assets:/app/assets
      - ./index.html:/app/index.html
      - ./about.html:/app/about.html
      - ./package.json:/app/package.json
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    command: "server"
